.editorconfig
.eslintrc
.gitignore
CHANGELOG.md
CONTRIBUTING.md
LICENSE
README.md
index.js
package.json
translations/ui-plugin-find-po-line/en.json

https://issues.folio.org/browse/UINV-24
project setup

UINV-24 project set up

---

translations/ui-plugin-find-po-line/ar.json
translations/ui-plugin-find-po-line/ca.json
translations/ui-plugin-find-po-line/da.json
translations/ui-plugin-find-po-line/de.json
translations/ui-plugin-find-po-line/en_GB.json
translations/ui-plugin-find-po-line/en_SE.json
translations/ui-plugin-find-po-line/en_US.json
translations/ui-plugin-find-po-line/es.json
translations/ui-plugin-find-po-line/es_419.json
translations/ui-plugin-find-po-line/es_ES.json
translations/ui-plugin-find-po-line/fr.json
translations/ui-plugin-find-po-line/fr_FR.json
translations/ui-plugin-find-po-line/hu.json
translations/ui-plugin-find-po-line/it_IT.json
translations/ui-plugin-find-po-line/pt_BR.json
translations/ui-plugin-find-po-line/pt_PT.json
translations/ui-plugin-find-po-line/zh_CN.json

Update translation strings as of 20190612T145704

---

translations/ui-plugin-find-po-line/pt_BR.json

Update translation strings as of 20190614T145022

---

translations/ui-plugin-find-po-line/ar.json

Update translation strings as of 20190618T141239

---

FindPOLine/FindPOLine.css
FindPOLine/FindPOLine.js
FindPOLine/FindPOLineModal/FindPOLineModal.css
FindPOLine/FindPOLineModal/FindPOLineModal.js
FindPOLine/FindPOLineModal/index.js
FindPOLine/index.js
Jenkinsfile
package.json
test/bigtest/.eslintrc
test/bigtest/helpers/PluginHarness.js
test/bigtest/helpers/helpers.js
test/bigtest/index.js
test/bigtest/interactors/application.js
test/bigtest/interactors/findPOLines.js
test/bigtest/network/index.js
test/bigtest/tests/findPOLines.e2e.js
translations/ui-plugin-find-po-line/en.json

https://issues.folio.org/browse/UINV-24

UINV-24 Search and select POL plugin

---

translations/ui-plugin-find-po-line/ar.json
translations/ui-plugin-find-po-line/ca.json
translations/ui-plugin-find-po-line/da.json
translations/ui-plugin-find-po-line/de.json
translations/ui-plugin-find-po-line/en_GB.json
translations/ui-plugin-find-po-line/en_SE.json
translations/ui-plugin-find-po-line/en_US.json
translations/ui-plugin-find-po-line/es.json
translations/ui-plugin-find-po-line/es_419.json
translations/ui-plugin-find-po-line/es_ES.json
translations/ui-plugin-find-po-line/fr.json
translations/ui-plugin-find-po-line/fr_FR.json
translations/ui-plugin-find-po-line/hu.json
translations/ui-plugin-find-po-line/it_IT.json
translations/ui-plugin-find-po-line/pt_BR.json
translations/ui-plugin-find-po-line/pt_PT.json
translations/ui-plugin-find-po-line/zh_CN.json

Update translation strings as of 20190624T123511

---

translations/ui-plugin-find-po-line/pt_BR.json

Update translation strings as of 20190625T144718

---

translations/ui-plugin-find-po-line/ar.json

Update translation strings as of 20190627T152539

---

package.json

UIOR-322-bump-interfaces

---

FindPOLine/FindPOLine.js
FindPOLine/FindPOLineModal/FindPOLineModal.js
README.md
package.json
test/bigtest/helpers/PluginHarnessSingleSelect.js
test/bigtest/helpers/helpers.js
test/bigtest/interactors/findPOLines.js
test/bigtest/tests/findPOLinesSingleSelect.e2e.js

https://issues.folio.org/browse/UIOR-320

UIOR-320 single select support

---

translations/ui-plugin-find-po-line/zh_CN.json

Update translation strings as of 20190729T163855

---

translations/ui-plugin-find-po-line/it_IT.json

Update translation strings as of 20190823T080157

---

translations/ui-plugin-find-po-line/ar.json

Update translation strings as of 20190828T124751

---

CHANGELOG.md
FindPOLine/FindPOLineContainer.js
package.json

https://issues.folio.org/browse/UIPFPOL-1

Release v1.1.0

---

translations/ui-plugin-find-po-line/it_IT.json

Update translation strings as of 20190913T225241

---

translations/ui-plugin-find-po-line/ru.json
translations/ui-plugin-find-po-line/zh_TW.json

Update translation strings as of 20191014T135140

---

translations/ui-plugin-find-po-line/ja.json

Update translation strings as of 20191028T205642

---

translations/ui-plugin-find-po-line/ru.json

Update translation strings as of 20191111T233434

---

translations/ui-plugin-find-po-line/he.json

Update translation strings as of 20191114T012425

---

translations/ui-plugin-find-po-line/fr_FR.json

Update translation strings as of 20191122T140350

---

translations/ui-plugin-find-po-line/fr_FR.json

Update translation strings as of 20191125T160504

---

translations/ui-plugin-find-po-line/fr_FR.json

Update translation strings as of 20191127T181804

---

translations/ui-plugin-find-po-line/es_ES.json

Update translation strings as of 20191220T155503

---

translations/ui-plugin-find-po-line/es.json
translations/ui-plugin-find-po-line/es_419.json

Update translation strings as of 20191220T210632

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIPFPOL-4

UIPFPOL-4: Update inventory okapiInterface to version 10.0

---

package.json

https://issues.folio.org/browse/MODORDERS-354
While it's helpful for reviewers to help …

MODORDERS-354 new okapi interfaces

---

translations/ui-plugin-find-po-line/it_IT.json

Update translation strings as of 20200203T164535

---

translations/ui-plugin-find-po-line/ur.json

Update translation strings as of 20200210T220102

---

package.json

bump up stripes v3

---

package.json

fix master build

---

CHANGELOG.md
FindPOLine/FindPOLineContainer.js
FindPOLine/FundFilter.js
FindPOLine/MaterialTypeFilter.js
FindPOLine/OrderLinesFilters.js
FindPOLine/OrdersLinesFilterConfig.js
FindPOLine/OrdersLinesSearchConfig.js
FindPOLine/OrdersTextFilter.js
FindPOLine/constants.js
package.json
test/bigtest/helpers/helpers.js

TECH-DEBT refactor ui-plugin-find-po-line to not use ui-orders
https://issues.folio.org/browse/UIPFPOL-7
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

UIPFPOL-7 remove dependency on ui-orders

---

translations/ui-plugin-find-po-line/ja.json

Update translation strings as of 20200413T183215

---

translations/ui-plugin-find-po-line/zh_TW.json

Update translation strings as of 20200505T210535

---

.gitignore
CHANGELOG.md
package.json

https://issues.folio.org/browse/UIPFPOL-9 …

UIPFPOL-9 Update to Stripes v4

---

translations/ui-plugin-find-po-line/zh_TW.json

Update translation strings as of 20200513T135229

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIORGS-178 …

UIORGS-178 Switch to mod-organizations

---

CHANGELOG.md
FindPOLine/FindPOLine.js
FindPOLine/FindPOLineContainer.js
FindPOLine/OrderLinesFilters.js
FindPOLine/OrdersLinesFilterConfig.js
FindPOLine/constants.js
test/bigtest/helpers/PluginHarnessInitialFilters.js
test/bigtest/helpers/helpers.js
test/bigtest/interactors/findPOLines.js
test/bigtest/tests/findPOLinesInitialFilters.e2e.js

https://issues.folio.org/browse/UIOR-564 …

UIOR-564 ability to provide default filters

---

FindPOLine/FindPOLine.js
README.md
package.json
test/bigtest/interactors/findPOLines.js
test/bigtest/tests/findPOLines.e2e.js

used interactor for Checkbox from stripes-components, so tests will fails if Checkbox is not clickable by user
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

add tests for checkbox

---

CHANGELOG.md
package.json

Upgrade stripes v5

---

translations/ui-plugin-find-po-line/hi_IN.json
translations/ui-plugin-find-po-line/ko.json

Update translation strings as of 20200921T192032

---

translations/ui-plugin-find-po-line/pl.json

Update translation strings as of 20200924T211627

---

test/bigtest/tests/findPOLines.e2e.js

fix random timeouts in test

---

translations/ui-plugin-find-po-line/ja.json

Update translation strings as of 20201102T140138

---

translations/ui-plugin-find-po-line/ber.json

Update translation strings as of 20201109T135508

---

CHANGELOG.md
PERSONAL_DATA_DISCLOSURE.md

https://issues.folio.org/browse/UIPFPOL-13 …

UIPFPOL-13 Add personal data disclosure form

---

package.json

bump up interface

---

package.json

https://issues.folio.org/browse/UIPFPOL-15 …

UIPFPOL-15 Update stripes-cli to v2

---

jest.config.js
package.json

FAT-46 Update jest config

---

CHANGELOG.md
package.json
test/bigtest/tests/findPOLinesSingleSelect.e2e.js

https://issues.folio.org/browse/UIPFPOL-12 …

Release v2.3.0

---

CHANGELOG.md
FindPOLine/OrdersLinesFilterConfig.js

https://issues.folio.org/browse/UIPFPOL-17 …

UIPFPOL-17 Fund code and Location filters not working for POL search

---

CHANGELOG.md
Jenkinsfile
package.json

https://issues.folio.org/browse/UIPFPOL-19 …

UIPFPOL-19 Compile Translation Files into AST Format

---

CHANGELOG.md
FindPOLine/constants.js

https://issues.folio.org/browse/UIPFPOL-20 …

UIPFPOL-20 Support cross index queries for GET /orders/order-lines endpoint

---

CHANGELOG.md
FindPOLine/FindPOLineContainer.js

https://issues.folio.org/browse/UIPFPOL-21 …

UIPFPO-21 Fix sorting by Title

---

CHANGELOG.md
FindPOLine/FindPOLineContainer.js
FindPOLine/OrdersLinesSearchConfig.js

https://issues.folio.org/browse/UIPFPOL-22 …

UIPFPOL-22 Display Vendor ref number column

---

CHANGELOG.md
FindPOLine/FindPOLineContainer.js

https://issues.folio.org/browse/UIPFPOL-25 …

UIPFPOL-25 Fund code and Location filters not working for POL search

---

package.json

bump up "finance.expense-classes" interface

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIPFPOL-24 …

UIPFPOL-24 increment stripes to v7

---

CHANGELOG.md
FindPOLine/OrderLinesFilters.js
FindPOLine/OrderLinesFilters.test.js

https://issues.folio.org/browse/UIPFPOL-28 …

UIPFPOL-28 Filter label contains extra 's'

---

package.json

Bump up interfaces

---

CHANGELOG.md
FindPOLine/ExpenseClassFilter/ExpenseClassFilter.js

https://issues.folio.org/browse/UIOR-870 …

UIOR-870 Update expense class filter to support multi-select

---

CHANGELOG.md
FindPOLine/OrderLinesFilters.js
FindPOLine/OrderLinesFilters.test.js
FindPOLine/OrdersLinesFilterConfig.js
FindPOLine/constants.js

https://issues.folio.org/browse/UIPFPOL-38 …

UIPFPOL-38 Filter orders lines by export date

---

FindPOLine/index.js

UIPFOL-34 export search config

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIPFPOL-52 …

UIPFPOL-52 Support `inventory` interface version `13.0`

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIPFPOL-53 …

UIPFPOL-53 bump stripes to 8.0.0 for Orchid/2023-R1

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
CHANGELOG.md
package.json

https://issues.folio.org/browse/UIPFPOL-59 …

UIPFPOL-59 Upgrade `Node` to `18` version

---

CHANGELOG.md
FindPOLine/OrderLinesFilters.js
FindPOLine/OrderLinesFilters.test.js
FindPOLine/constants.js
FindPOLine/utils.js

[UIPFPOL-65](https://issues.folio.org/browse/UIPFPOL-65) - Add donors filter
Dependent PRs:
- https://github.com/folio-org/stripes-acq-components/pull/732 
- https://github.com/folio-org/ui-orders/pull/1528
https://github.com/folio-org/ui-plugin-find-po-line/assets/116072773/2e0b1b69-466c-46ab-bafa-0069a2b3f804
Ideally all of the PRs involved in breaking …

UIPFPOL-65: add Donor Filter

---

CHANGELOG.md
FindPOLine/OrderLinesFilters.js
FindPOLine/OrderLinesFilters.test.js
FindPOLine/utils.js
FindPOLine/utils.test.js

[UIPFPOL-66](https://folio-org.atlassian.net/browse/UIPFPOL-66) - Fix date range-related filters due to sending dates as an `Array` while the expected result must be in `String`.
https://github.com/folio-org/ui-plugin-find-po-line/assets/116072773/7603b7d8-6e8c-499a-af42-a9053cbcde66
Ideally all of the PRs involved in breaking changes would be merged in …

UIPFPOL-66: fix date range related filter not working due to sending `array` type

---

FindPOLine/OrderLinesFilters.js
FindPOLine/OrderLinesFilters.test.js

[UIPFPOL-66](https://folio-org.atlassian.net/browse/UIPFPOL-66) - fix: selected date range issue
Comment - [UIPFPOL-66](https://folio-org.atlassian.net/browse/UIPFPOL-66?focusedCommentId=203676)
https://github.com/folio-org/ui-plugin-find-po-line/assets/116072773/2c756dd2-8840-470d-a861-f39630188617
Ideally all of the PRs involved in breaking changes would …

fix: selected date range issue

---

CHANGELOG.md
package.json

https://folio-org.atlassian.net/browse/UIPFPOL-68

UIPFPOL-68 Align the 'finance.fund' interface version (3.0)

---

CHANGELOG.md
FindPOLine/OrderLinesFilters.js
FindPOLine/constants.js
FindPOLine/utils.js

https://folio-org.atlassian.net/browse/UIPFPOL-71 - Add additional order filters to support reporting requirements
https://github.com/folio-org/ui-plugin-find-po-line/assets/116072773/5bc3efc4-c61a-4c2d-97cf-3e468d273496
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …

UIPFPOL-71: Add additional order filters to support reporting requirements

---

CHANGELOG.md
FindPOLine/utils.js
FindPOLine/utils.test.js

https://folio-org.atlassian.net/browse/UIPFPOL-72
https://github.com/folio-org/ui-plugin-find-po-line/assets/88109087/f3ca47e7-c771-4d80-9355-79cc3f22e643
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

UIPFPOL-72 Update the order lines query with location filtering to include the `searchLocationIds` field

---

CHANGELOG.md
FindPOLine/FindPOLine.js
FindPOLine/OrderLinesFilters.js
package.json

https://folio-org.atlassian.net/browse/UIPFPOL-74
Since the filter is now a multi-select, it requires passing the current value of the filter (which is an array), not just one element from it. Also make it possible to pass the `crossTenant` flag, which will allow searching for locations in different tenants.
--
Should be merged after: 
- https://github.com/folio-org/stripes-acq-components/pull/775
Should be merged before: 
- https://github.com/folio-org/ui-orders/pull/1602
https://github.com/folio-org/ui-plugin-find-po-line/assets/88109087/2094db93-7798-4803-91ce-58bc75077075
If there are breaking …

UIPFPOL-74 Adjust location filter to support cross-tenant search

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml
FindPOLine/MaterialTypeFilter.test.js
FindPOLine/PrefixFilter/PrefixFilter.test.js
FindPOLine/SuffixFilter/SuffixFilter.test.js
package.json

UIPFPOL-81 inventory API version update

---

CHANGELOG.md
FindPOLine/constants.js
FindPOLine/utils.js

[UIPFPOL-82](https://folio-org.atlassian.net/browse/UIOR-1270): Add the ability to search for purchase order lines by multiple funds
https://github.com/user-attachments/assets/8d80dd72-59c3-4fd9-a157-4becfaab79f2
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …

UIPFPOL-82: Add the ability to search for purchase order lines by multiple funds

---

FindPOLine/utils.js

UIPFPOL-82: optimize the `fundDistribution` query using index According to the ticket https://folio-org.atlassian.net/browse/UIPFPOL-57
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

UIPFPOL-82: optimize the fundDistribution query using index

---

CHANGELOG.md
FindPOLine/AcqMethodsFilter/AcqMethodsFilter.js
FindPOLine/FindPOLine.js
FindPOLine/LinkedPackagePOLineFilter/LinkedPackagePOLineFilter.js
FindPOLine/OrdersTextFilter.js

UIPFPOL-78 React v19: refactor away from default props for functional components

---

CHANGELOG.md
FindPOLine/OrderLinesSearchConfig.js
FindPOLine/OrderLinesSearchConfig.test.js
FindPOLine/utils.js

https://folio-org.atlassian.net/browse/UIPFPOL-89
https://github.com/user-attachments/assets/b0ea988c-2af1-461a-a758-f38aba030c9a
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …

UIPFPOL-89 Change query template for product IDs to optimize requests

---

package.json

[MODORDERS-1269](https://folio-org.atlassian.net/browse/MODORDERS-1269) - Remove alerts and reporting codes from order lines, use a single order line schema
Updated order-lines interface version
[Related PRs](https://github.com/folio-org/mod-orders-storage/pull/477)
Ideally all of the PRs involved in breaking changes would be merged in the same day to …

[MODORDERS-1269] Updated order-lines interface version
